ALTER TABLE PAGOJRV.ESTADO
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAGOJRV.ESTADO CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.ESTADO
(
  ID_ESTADO_DIGITADA  INTEGER                   NOT NULL,
  ESTADO_DIGITADA     VARCHAR2(30 BYTE)         NOT NULL
)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PAGOJRV.IMAGEN
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAGOJRV.IMAGEN CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.IMAGEN
(
  JRV                 INTEGER                   NOT NULL,
  IMAGEN_ALCALDE      BLOB,
  IMAGEN_DIPUTADO     BLOB,
  IMAGEN_PRESIDENTE   BLOB,
  ID_ESTADO_DIGITADA  INTEGER
)
LOB (IMAGEN_ALCALDE) STORE AS (
  TABLESPACE  TBS_PAGOJRV
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (IMAGEN_PRESIDENTE) STORE AS (
  TABLESPACE  TBS_PAGOJRV
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (IMAGEN_DIPUTADO) STORE AS (
  TABLESPACE  TBS_PAGOJRV
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PAGOJRV.PADRON
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAGOJRV.PADRON CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.PADRON
(
  DUI        INTEGER                            NOT NULL,
  NOMBRES    VARCHAR2(255 BYTE)                 NOT NULL,
  APELLIDOS  VARCHAR2(255 BYTE)                 NOT NULL
)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PAGOJRV.PARTIDO_POLITICO
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAGOJRV.PARTIDO_POLITICO CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.PARTIDO_POLITICO
(
  ID_PARTIDO  INTEGER                           NOT NULL,
  PARTIDO     VARCHAR2(255 BYTE)                NOT NULL
)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PAGOJRV.TIPO_CARGO
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAGOJRV.TIPO_CARGO CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.TIPO_CARGO
(
  ID_TIPO_CARGO  INTEGER                        NOT NULL,
  CARGO          VARCHAR2(30 BYTE)              NOT NULL
)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PAGOJRV.TIPO_INCONSISTENCIA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAGOJRV.TIPO_INCONSISTENCIA CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.TIPO_INCONSISTENCIA
(
  ID_TIPO_INCONSISTENCIA  INTEGER               NOT NULL,
  INCONSISTENCIA          VARCHAR2(30 BYTE)     NOT NULL
)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PAGOJRV.USUARIO
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAGOJRV.USUARIO CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.USUARIO
(
  ID_USUARIO  INTEGER                           NOT NULL,
  NOMBRE      VARCHAR2(255 BYTE)                NOT NULL,
  CONTRASEÑA  CHAR(20 BYTE)                     NOT NULL
)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAGOJRV.KEYN ON PAGOJRV.ESTADO
(ID_ESTADO_DIGITADA)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAGOJRV.IX_RELATIONSHIP19 ON PAGOJRV.IMAGEN
(ID_ESTADO_DIGITADA)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAGOJRV.KEYA ON PAGOJRV.IMAGEN
(JRV)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAGOJRV.KEY2 ON PAGOJRV.PADRON
(DUI)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAGOJRV.KEYS ON PAGOJRV.USUARIO
(ID_USUARIO)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAGOJRV.KEYZ ON PAGOJRV.TIPO_CARGO
(ID_TIPO_CARGO)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAGOJRV.KEYX ON PAGOJRV.TIPO_INCONSISTENCIA
(ID_TIPO_INCONSISTENCIA)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAGOJRV.KEYC_PARTIDO ON PAGOJRV.PARTIDO_POLITICO
(ID_PARTIDO)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAGOJRV.PRIMER_DIGITADA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAGOJRV.PRIMER_DIGITADA CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.PRIMER_DIGITADA
(
  DUI_DIGITADO1           VARCHAR2(10 BYTE)     NOT NULL,
  NOMBRES                 CHAR(20 BYTE)         NOT NULL,
  APELLIDOS               CHAR(20 BYTE)         NOT NULL,
  ID_PARTIDO              INTEGER               NOT NULL,
  ID_USUARIO              INTEGER               NOT NULL,
  JRV                     INTEGER               NOT NULL,
  ID_TIPO_INCONSISTENCIA  INTEGER               NOT NULL,
  ID_TIPO_CARGO           INTEGER               NOT NULL
)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PAGOJRV.SEGUNDA_DIGITADA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PAGOJRV.SEGUNDA_DIGITADA CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.SEGUNDA_DIGITADA
(
  DUI_DIGITADO            CHAR(20 BYTE)         NOT NULL,
  NOMBRES                 CHAR(20 BYTE)         NOT NULL,
  APELLIDOS               CHAR(20 BYTE)         NOT NULL,
  ID_PARTIDO              INTEGER               NOT NULL,
  ID_USUARIO              INTEGER               NOT NULL,
  JRV                     INTEGER               NOT NULL,
  ID_TIPO_INCONSISTENCIA  INTEGER               NOT NULL,
  ID_TIPO_CARGO           INTEGER               NOT NULL
)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PAGOJRV.KEYV ON PAGOJRV.PRIMER_DIGITADA
(ID_PARTIDO, ID_USUARIO, JRV, ID_TIPO_INCONSISTENCIA, ID_TIPO_CARGO, 
DUI_DIGITADO1)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PAGOJRV.KEYB ON PAGOJRV.SEGUNDA_DIGITADA
(DUI_DIGITADO, ID_PARTIDO, ID_USUARIO, JRV, ID_TIPO_INCONSISTENCIA, 
ID_TIPO_CARGO)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


DROP TABLE PAGOJRV.COINCIDENTES CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.COINCIDENTES
(
  DUI_DIGITADO            CHAR(20 BYTE),
  ID_PARTIDO              INTEGER,
  ID_USUARIO              INTEGER,
  JRV                     INTEGER,
  ID_TIPO_INCONSISTENCIA  INTEGER,
  ID_TIPO_CARGO           INTEGER
)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PAGOJRV.INCONSISTENTES CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.INCONSISTENTES
(
  DUI_DIGITADO            CHAR(20 BYTE),
  ID_PARTIDO              INTEGER,
  ID_USUARIO              INTEGER,
  JRV                     INTEGER,
  ID_TIPO_INCONSISTENCIA  INTEGER,
  ID_TIPO_CARGO           INTEGER
)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PAGOJRV.RECHAZADOS CASCADE CONSTRAINTS;

CREATE TABLE PAGOJRV.RECHAZADOS
(
  DUI_DIGITADO            CHAR(20 BYTE),
  ID_PARTIDO              INTEGER,
  ID_USUARIO              INTEGER,
  JRV                     INTEGER,
  ID_TIPO_INCONSISTENCIA  INTEGER,
  ID_TIPO_CARGO           INTEGER
)
TABLESPACE TBS_PAGOJRV
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PAGOJRV.IX_RELATIONSHIP8 ON PAGOJRV.COINCIDENTES
(DUI_DIGITADO, ID_PARTIDO, ID_USUARIO, JRV, ID_TIPO_INCONSISTENCIA, 
ID_TIPO_CARGO)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAGOJRV.IX_RELATIONSHIP6 ON PAGOJRV.INCONSISTENTES
(DUI_DIGITADO, ID_PARTIDO, ID_USUARIO, JRV, ID_TIPO_INCONSISTENCIA, 
ID_TIPO_CARGO)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX PAGOJRV.IX_RELATIONSHIP7 ON PAGOJRV.RECHAZADOS
(DUI_DIGITADO, ID_PARTIDO, ID_USUARIO, JRV, ID_TIPO_INCONSISTENCIA, 
ID_TIPO_CARGO)
LOGGING
TABLESPACE TBS_PAGOJRV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAGOJRV.ESTADO ADD (
  CONSTRAINT KEYN
  PRIMARY KEY
  (ID_ESTADO_DIGITADA)
  USING INDEX PAGOJRV.KEYN
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.IMAGEN ADD (
  CONSTRAINT KEYA
  PRIMARY KEY
  (JRV)
  USING INDEX PAGOJRV.KEYA
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.PADRON ADD (
  CONSTRAINT KEY2
  PRIMARY KEY
  (DUI)
  USING INDEX PAGOJRV.KEY2
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.PARTIDO_POLITICO ADD (
  CONSTRAINT KEYC_PARTIDO
  PRIMARY KEY
  (ID_PARTIDO)
  USING INDEX PAGOJRV.KEYC_PARTIDO
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.TIPO_CARGO ADD (
  CONSTRAINT KEYZ
  PRIMARY KEY
  (ID_TIPO_CARGO)
  USING INDEX PAGOJRV.KEYZ
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.TIPO_INCONSISTENCIA ADD (
  CONSTRAINT KEYX
  PRIMARY KEY
  (ID_TIPO_INCONSISTENCIA)
  USING INDEX PAGOJRV.KEYX
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.USUARIO ADD (
  CONSTRAINT KEYS
  PRIMARY KEY
  (ID_USUARIO)
  USING INDEX PAGOJRV.KEYS
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.PRIMER_DIGITADA ADD (
  CONSTRAINT KEYV
  PRIMARY KEY
  (ID_PARTIDO, ID_USUARIO, JRV, ID_TIPO_INCONSISTENCIA, ID_TIPO_CARGO, DUI_DIGITADO1)
  USING INDEX PAGOJRV.KEYV
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.SEGUNDA_DIGITADA ADD (
  CONSTRAINT KEYB
  PRIMARY KEY
  (DUI_DIGITADO, ID_PARTIDO, ID_USUARIO, JRV, ID_TIPO_INCONSISTENCIA, ID_TIPO_CARGO)
  USING INDEX PAGOJRV.KEYB
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.IMAGEN ADD (
  CONSTRAINT RELATIONSHIP19 
  FOREIGN KEY (ID_ESTADO_DIGITADA) 
  REFERENCES PAGOJRV.ESTADO (ID_ESTADO_DIGITADA)
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.PRIMER_DIGITADA ADD (
  CONSTRAINT RELATIONSHIP10 
  FOREIGN KEY (ID_PARTIDO) 
  REFERENCES PAGOJRV.PARTIDO_POLITICO (ID_PARTIDO)
  ENABLE VALIDATE,
  CONSTRAINT RELATIONSHIP11 
  FOREIGN KEY (ID_USUARIO) 
  REFERENCES PAGOJRV.USUARIO (ID_USUARIO)
  ENABLE VALIDATE,
  CONSTRAINT RELATIONSHIP12 
  FOREIGN KEY (JRV) 
  REFERENCES PAGOJRV.IMAGEN (JRV)
  ENABLE VALIDATE,
  CONSTRAINT RELATIONSHIP14 
  FOREIGN KEY (ID_TIPO_INCONSISTENCIA) 
  REFERENCES PAGOJRV.TIPO_INCONSISTENCIA (ID_TIPO_INCONSISTENCIA)
  ENABLE VALIDATE,
  CONSTRAINT RELATIONSHIP17 
  FOREIGN KEY (ID_TIPO_CARGO) 
  REFERENCES PAGOJRV.TIPO_CARGO (ID_TIPO_CARGO)
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.SEGUNDA_DIGITADA ADD (
  CONSTRAINT RELATIONSHIP1 
  FOREIGN KEY (ID_PARTIDO) 
  REFERENCES PAGOJRV.PARTIDO_POLITICO (ID_PARTIDO)
  ENABLE VALIDATE,
  CONSTRAINT RELATIONSHIP16 
  FOREIGN KEY (ID_TIPO_CARGO) 
  REFERENCES PAGOJRV.TIPO_CARGO (ID_TIPO_CARGO)
  ENABLE VALIDATE,
  CONSTRAINT RELATIONSHIP2 
  FOREIGN KEY (ID_USUARIO) 
  REFERENCES PAGOJRV.USUARIO (ID_USUARIO)
  ENABLE VALIDATE,
  CONSTRAINT RELATIONSHIP3 
  FOREIGN KEY (JRV) 
  REFERENCES PAGOJRV.IMAGEN (JRV)
  ENABLE VALIDATE,
  CONSTRAINT RELATIONSHIP9 
  FOREIGN KEY (ID_TIPO_INCONSISTENCIA) 
  REFERENCES PAGOJRV.TIPO_INCONSISTENCIA (ID_TIPO_INCONSISTENCIA)
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.COINCIDENTES ADD (
  CONSTRAINT RELATIONSHIP8 
  FOREIGN KEY (DUI_DIGITADO, ID_PARTIDO, ID_USUARIO, JRV, ID_TIPO_INCONSISTENCIA, ID_TIPO_CARGO) 
  REFERENCES PAGOJRV.SEGUNDA_DIGITADA (DUI_DIGITADO,ID_PARTIDO,ID_USUARIO,JRV,ID_TIPO_INCONSISTENCIA,ID_TIPO_CARGO)
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.INCONSISTENTES ADD (
  CONSTRAINT RELATIONSHIP6 
  FOREIGN KEY (DUI_DIGITADO, ID_PARTIDO, ID_USUARIO, JRV, ID_TIPO_INCONSISTENCIA, ID_TIPO_CARGO) 
  REFERENCES PAGOJRV.SEGUNDA_DIGITADA (DUI_DIGITADO,ID_PARTIDO,ID_USUARIO,JRV,ID_TIPO_INCONSISTENCIA,ID_TIPO_CARGO)
  ENABLE VALIDATE);

ALTER TABLE PAGOJRV.RECHAZADOS ADD (
  CONSTRAINT RELATIONSHIP7 
  FOREIGN KEY (DUI_DIGITADO, ID_PARTIDO, ID_USUARIO, JRV, ID_TIPO_INCONSISTENCIA, ID_TIPO_CARGO) 
  REFERENCES PAGOJRV.SEGUNDA_DIGITADA (DUI_DIGITADO,ID_PARTIDO,ID_USUARIO,JRV,ID_TIPO_INCONSISTENCIA,ID_TIPO_CARGO)
  ENABLE VALIDATE);
